import os
import sys
import nanoid
from bitkub import Bitkub
from libraries.recommendation import Recommendation, TimeInterval
from libraries.logs import Logs
import mysql.connector
from dotenv import load_dotenv

# initialize
load_dotenv()
API_HOST = os.environ.get('BITKUB_HOST')
API_KEY = os.environ.get('BITKUB_KEY')
API_SECRET = os.environ.get('BITKUB_SECRET')

bitkub = Bitkub(API_KEY, API_SECRET)
recommendation = Recommendation()
timeInterval = TimeInterval()

mydb = mysql.connector.connect(
    host=os.environ.get('MYSQL_HOST'),
    user=os.environ.get('MYSQL_USERNAME'),
    password=os.environ.get('MYSQL_PASSWORD'),
    database=os.environ.get('MYSQL_DBNAME')
)

log = Logs()
investment = []


def main():
    symbols = bitkub.symbols()
    result = symbols['result']
    i = 0
    while i < len(result):
        sym = str(result[i]['symbol'])[len('THB_'):]
        ticker = bitkub.ticker(sym=f'THB_{sym}')
        last_price = 0
        last_percent = 0
        if len(ticker) > 0:
            data = ticker[f'THB_{sym}']
            last_price = data['last']
            last_percent = data['percentChange']

        log.print_color(f'{(i + 1)}. {sym}')
        percent = ((i + 1) * 100) / len(result)
        strategy = []
        profit_score = len(timeInterval.get_interval())
        for x in timeInterval.get_interval():
            comment = recommendation.summary(symbol=sym, quote='THB', interval=x)
            summary = comment['RECOMMENDATION']
            comment = recommendation.moving_averages(symbol=sym, quote='THB', interval=x)
            mcd = comment['RECOMMENDATION']

            strategy.append({
                'time_frame': x,
                'strategy_summary': summary,
                'strategy_macd': mcd,
            })

            if summary == mcd:
                if summary == 'BUY':
                    profit_score += 1

                elif summary == 'STRONG_BUY':
                    profit_score += 0.5

                elif summary == 'SELL':
                    profit_score -= 0.5

                elif summary == 'STRONG_SELL':
                    profit_score -= 1

            else:
                profit_score -= 1

        comment = recommendation.summary(symbol=sym, quote='THB')
        trend = comment['RECOMMENDATION']
        log.print_color(f'score :=> {profit_score}')
        log.print_color(f'PRICE :=> {last_price} THB')
        log.print_color(f'PERCENT CHANGE :=> {last_percent}%')
        log.print_color(f"STRATEGY:")
        print(list(strategy))
        log.print_color(f"PERCENT LOOP: {percent}%")
        is_interest = False
        if profit_score >= 3.5:
            is_interest = True

        investment.append({
            'symbol': sym,
            'exchange': 'BITKUB',
            'last_price': last_price,
            'percent_change': last_percent,
            'technicals': trend,
            'is_interest': is_interest,
            'is_opened': False,
            'strategy': strategy
        })
        print("\n")
        i += 1


def insert_interest():
    interest = [
        {'symbol': 'BTC', 'exchange': 'BITKUB', 'last_price': 1205044.55, 'percent_change': -5.79,
         'technicals': 'STRONG_SELL', 'is_interest': False, 'is_opened': False,
         'strategy': [{'time_frame': '30m', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '2h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '4h', 'strategy_summary': 'STRONG_SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1d', 'strategy_summary': 'STRONG_SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1W', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1M', 'strategy_summary': 'SELL', 'strategy_macd': 'NEUTRAL'}]},
        {'symbol': 'ETH', 'exchange': 'BITKUB', 'last_price': 82629.93, 'percent_change': -7.77,
         'technicals': 'SELL', 'is_interest': False, 'is_opened': False,
         'strategy': [{'time_frame': '30m', 'strategy_summary': 'STRONG_SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '2h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '4h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1d', 'strategy_summary': 'STRONG_SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1W', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1M', 'strategy_summary': 'BUY', 'strategy_macd': 'BUY'}]},
        {'symbol': 'WAN', 'exchange': 'BITKUB', 'last_price': 11.53, 'percent_change': -12.92,
         'technicals': 'SELL', 'is_interest': False, 'is_opened': False,
         'strategy': [{'time_frame': '30m', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '2h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '4h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1d', 'strategy_summary': 'STRONG_SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1W', 'strategy_summary': 'STRONG_SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1M', 'strategy_summary': 'STRONG_SELL', 'strategy_macd': 'STRONG_SELL'}]},
        {'symbol': 'ADA', 'exchange': 'BITKUB', 'last_price': 27.23, 'percent_change': -14.29,
         'technicals': 'SELL', 'is_interest': False, 'is_opened': False,
         'strategy': [{'time_frame': '30m', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '2h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '4h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1d', 'strategy_summary': 'STRONG_SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1W', 'strategy_summary': 'STRONG_SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1M', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'}]},
        {'symbol': 'OMG', 'exchange': 'BITKUB', 'last_price': 124, 'percent_change': -10.61,
         'technicals': 'SELL', 'is_interest': False, 'is_opened': False,
         'strategy': [{'time_frame': '30m', 'strategy_summary': 'SELL', 'strategy_macd': 'SELL'},
                      {'time_frame': '1h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '2h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '4h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1d', 'strategy_summary': 'STRONG_SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1W', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1M', 'strategy_summary': 'STRONG_SELL', 'strategy_macd': 'STRONG_SELL'}]},
        {'symbol': 'BCH', 'exchange': 'BITKUB', 'last_price': 9231.23, 'percent_change': -7.85,
         'technicals': 'SELL', 'is_interest': False, 'is_opened': False,
         'strategy': [{'time_frame': '30m', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '2h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '4h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1d', 'strategy_summary': 'STRONG_SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1W', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1M', 'strategy_summary': 'STRONG_SELL', 'strategy_macd': 'STRONG_SELL'}]},
        {'symbol': 'USDT', 'exchange': 'BITKUB', 'last_price': 32.79, 'percent_change': 0.43,
         'technicals': 'BUY', 'is_interest': True, 'is_opened': False,
         'strategy': [{'time_frame': '30m', 'strategy_summary': 'BUY', 'strategy_macd': 'BUY'},
                      {'time_frame': '1h', 'strategy_summary': 'BUY', 'strategy_macd': 'STRONG_BUY'},
                      {'time_frame': '2h', 'strategy_summary': 'BUY', 'strategy_macd': 'STRONG_BUY'},
                      {'time_frame': '4h', 'strategy_summary': 'BUY', 'strategy_macd': 'BUY'},
                      {'time_frame': '1d', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1W', 'strategy_summary': 'NEUTRAL', 'strategy_macd': 'SELL'},
                      {'time_frame': '1M', 'strategy_summary': 'BUY', 'strategy_macd': 'BUY'}]},
        {'symbol': 'LTC', 'exchange': 'BITKUB', 'last_price': 3346.55, 'percent_change': -9.7,
         'technicals': 'SELL', 'is_interest': False, 'is_opened': False,
         'strategy': [{'time_frame': '30m', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '2h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '4h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1d', 'strategy_summary': 'STRONG_SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1W', 'strategy_summary': 'STRONG_SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1M', 'strategy_summary': 'STRONG_SELL', 'strategy_macd': 'STRONG_SELL'}]},
        {'symbol': 'XRP', 'exchange': 'BITKUB', 'last_price': 22.48, 'percent_change': -13.67,
         'technicals': 'SELL', 'is_interest': False, 'is_opened': False,
         'strategy': [{'time_frame': '30m', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '2h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '4h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1d', 'strategy_summary': 'STRONG_SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1W', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1M', 'strategy_summary': 'SELL', 'strategy_macd': 'SELL'}]},
        {'symbol': 'ZIL', 'exchange': 'BITKUB', 'last_price': 1.2884, 'percent_change': -12.62,
         'technicals': 'SELL', 'is_interest': False, 'is_opened': False,
         'strategy': [{'time_frame': '30m', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '2h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '4h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1d', 'strategy_summary': 'STRONG_SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1W', 'strategy_summary': 'STRONG_SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1M', 'strategy_summary': 'STRONG_SELL', 'strategy_macd': 'STRONG_SELL'}]},
        {'symbol': 'SNT', 'exchange': 'BITKUB', 'last_price': 1.55, 'percent_change': -12.43,
         'technicals': 'SELL', 'is_interest': False, 'is_opened': False,
         'strategy': [{'time_frame': '30m', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '2h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '4h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1d', 'strategy_summary': 'STRONG_SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1W', 'strategy_summary': 'STRONG_SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1M', 'strategy_summary': 'STRONG_SELL', 'strategy_macd': 'STRONG_SELL'}]},
        {'symbol': 'CVC', 'exchange': 'BITKUB', 'last_price': 7.42, 'percent_change': -13.62,
         'technicals': 'SELL', 'is_interest': False, 'is_opened': False,
         'strategy': [{'time_frame': '30m', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '2h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '4h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1d', 'strategy_summary': 'STRONG_SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1W', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1M', 'strategy_summary': 'SELL', 'strategy_macd': 'SELL'}]},
        {'symbol': 'LINK', 'exchange': 'BITKUB', 'last_price': 435.05, 'percent_change': -12.11,
         'technicals': 'SELL', 'is_interest': False, 'is_opened': False,
         'strategy': [{'time_frame': '30m', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '2h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '4h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1d', 'strategy_summary': 'STRONG_SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1W', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1M', 'strategy_summary': 'STRONG_SELL', 'strategy_macd': 'STRONG_SELL'}]},
        {'symbol': 'IOST', 'exchange': 'BITKUB', 'last_price': 0.7, 'percent_change': -10.26,
         'technicals': 'SELL', 'is_interest': False, 'is_opened': False,
         'strategy': [{'time_frame': '30m', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '2h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '4h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1d', 'strategy_summary': 'STRONG_SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1W', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1M', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'}]},
        {'symbol': 'ZRX', 'exchange': 'BITKUB', 'last_price': 16.89, 'percent_change': -11.43,
         'technicals': 'SELL', 'is_interest': False, 'is_opened': False,
         'strategy': [{'time_frame': '30m', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '2h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '4h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1d', 'strategy_summary': 'STRONG_SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1W', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1M', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'}]},
        {'symbol': 'KNC', 'exchange': 'BITKUB', 'last_price': 55.18, 'percent_change': -18.69,
         'technicals': 'SELL', 'is_interest': False, 'is_opened': False,
         'strategy': [{'time_frame': '30m', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '2h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '4h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1d', 'strategy_summary': 'STRONG_SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1W', 'strategy_summary': 'SELL', 'strategy_macd': 'SELL'},
                      {'time_frame': '1M', 'strategy_summary': 'SELL', 'strategy_macd': 'NEUTRAL'}]},
        {'symbol': 'ABT', 'exchange': 'BITKUB', 'last_price': 5.01, 'percent_change': -10.22,
         'technicals': 'STRONG_SELL', 'is_interest': False, 'is_opened': False,
         'strategy': [{'time_frame': '30m', 'strategy_summary': 'STRONG_SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '2h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '4h', 'strategy_summary': 'STRONG_SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1d', 'strategy_summary': 'STRONG_SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1W', 'strategy_summary': 'STRONG_SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1M', 'strategy_summary': 'SELL', 'strategy_macd': 'SELL'}]},
        {'symbol': 'MANA', 'exchange': 'BITKUB', 'last_price': 80.57, 'percent_change': -15.47,
         'technicals': 'SELL', 'is_interest': False, 'is_opened': False,
         'strategy': [{'time_frame': '30m', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '2h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '4h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1d', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1W', 'strategy_summary': 'NEUTRAL', 'strategy_macd': 'NEUTRAL'},
                      {'time_frame': '1M', 'strategy_summary': 'BUY', 'strategy_macd': 'STRONG_BUY'}]},
        {'symbol': 'CTXC', 'exchange': 'BITKUB', 'last_price': 0, 'percent_change': 0, 'technicals': '',
         'is_interest': True, 'is_opened': False,
         'strategy': [{'time_frame': '30m', 'strategy_summary': '', 'strategy_macd': ''},
                      {'time_frame': '1h', 'strategy_summary': '', 'strategy_macd': ''},
                      {'time_frame': '2h', 'strategy_summary': '', 'strategy_macd': ''},
                      {'time_frame': '4h', 'strategy_summary': '', 'strategy_macd': ''},
                      {'time_frame': '1d', 'strategy_summary': '', 'strategy_macd': ''},
                      {'time_frame': '1W', 'strategy_summary': '', 'strategy_macd': ''},
                      {'time_frame': '1M', 'strategy_summary': '', 'strategy_macd': ''}]},
        {'symbol': 'XLM', 'exchange': 'BITKUB', 'last_price': 5.8, 'percent_change': -10.91,
         'technicals': 'SELL', 'is_interest': False, 'is_opened': False,
         'strategy': [{'time_frame': '30m', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '2h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '4h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1d', 'strategy_summary': 'STRONG_SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1W', 'strategy_summary': 'STRONG_SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1M', 'strategy_summary': 'STRONG_SELL', 'strategy_macd': 'STRONG_SELL'}]},
        {'symbol': 'SIX', 'exchange': 'BITKUB', 'last_price': 5.4544, 'percent_change': -12.39,
         'technicals': 'SELL', 'is_interest': False, 'is_opened': False,
         'strategy': [{'time_frame': '30m', 'strategy_summary': 'STRONG_SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '2h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '4h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1d', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1W', 'strategy_summary': 'NEUTRAL', 'strategy_macd': 'NEUTRAL'},
                      {'time_frame': '1M', 'strategy_summary': 'BUY', 'strategy_macd': 'STRONG_BUY'}]},
        {'symbol': 'JFIN', 'exchange': 'BITKUB', 'last_price': 63.23, 'percent_change': -13.97,
         'technicals': 'STRONG_SELL', 'is_interest': False, 'is_opened': False,
         'strategy': [{'time_frame': '30m', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '2h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '4h', 'strategy_summary': 'STRONG_SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1d', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1W', 'strategy_summary': 'NEUTRAL', 'strategy_macd': 'NEUTRAL'},
                      {'time_frame': '1M', 'strategy_summary': 'BUY', 'strategy_macd': 'BUY'}]},
        {'symbol': 'BNB', 'exchange': 'BITKUB', 'last_price': 11703.04, 'percent_change': -8.93,
         'technicals': 'SELL', 'is_interest': False, 'is_opened': False,
         'strategy': [{'time_frame': '30m', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '2h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '4h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1d', 'strategy_summary': 'STRONG_SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1W', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1M', 'strategy_summary': 'NEUTRAL', 'strategy_macd': 'NEUTRAL'}]},
        {'symbol': 'POW', 'exchange': 'BITKUB', 'last_price': 14.9, 'percent_change': -14.07,
         'technicals': 'SELL', 'is_interest': False, 'is_opened': False,
         'strategy': [{'time_frame': '30m', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '2h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '4h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1d', 'strategy_summary': 'STRONG_SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1W', 'strategy_summary': 'SELL', 'strategy_macd': 'SELL'},
                      {'time_frame': '1M', 'strategy_summary': 'BUY', 'strategy_macd': 'STRONG_BUY'}]},
        {'symbol': 'DOGE', 'exchange': 'BITKUB', 'last_price': 4.1611, 'percent_change': -8.75,
         'technicals': 'SELL', 'is_interest': False, 'is_opened': False,
         'strategy': [{'time_frame': '30m', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '2h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '4h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1d', 'strategy_summary': 'STRONG_SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1W', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1M', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'}]},
        {'symbol': 'DAI', 'exchange': 'BITKUB', 'last_price': 32.6, 'percent_change': 0.03,
         'technicals': 'NEUTRAL', 'is_interest': False, 'is_opened': False,
         'strategy': [{'time_frame': '30m', 'strategy_summary': 'BUY', 'strategy_macd': 'STRONG_BUY'},
                      {'time_frame': '1h', 'strategy_summary': 'STRONG_BUY', 'strategy_macd': 'STRONG_BUY'},
                      {'time_frame': '2h', 'strategy_summary': 'BUY', 'strategy_macd': 'STRONG_BUY'},
                      {'time_frame': '4h', 'strategy_summary': 'NEUTRAL', 'strategy_macd': 'BUY'},
                      {'time_frame': '1d', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1W', 'strategy_summary': 'NEUTRAL', 'strategy_macd': 'SELL'},
                      {'time_frame': '1M', 'strategy_summary': 'NEUTRAL', 'strategy_macd': 'NEUTRAL'}]},
        {'symbol': 'USDC', 'exchange': 'BITKUB', 'last_price': 32.75, 'percent_change': 1.14,
         'technicals': 'BUY', 'is_interest': False, 'is_opened': False,
         'strategy': [{'time_frame': '30m', 'strategy_summary': 'BUY', 'strategy_macd': 'STRONG_BUY'},
                      {'time_frame': '1h', 'strategy_summary': 'BUY', 'strategy_macd': 'STRONG_BUY'},
                      {'time_frame': '2h', 'strategy_summary': 'BUY', 'strategy_macd': 'STRONG_BUY'},
                      {'time_frame': '4h', 'strategy_summary': 'BUY', 'strategy_macd': 'BUY'},
                      {'time_frame': '1d', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1W', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1M', 'strategy_summary': 'STRONG_SELL', 'strategy_macd': 'STRONG_SELL'}]},
        {'symbol': 'BAT', 'exchange': 'BITKUB', 'last_price': 21.29, 'percent_change': -11.29,
         'technicals': 'SELL', 'is_interest': False, 'is_opened': False,
         'strategy': [{'time_frame': '30m', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '2h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '4h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1d', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1W', 'strategy_summary': 'STRONG_SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1M', 'strategy_summary': 'STRONG_SELL', 'strategy_macd': 'STRONG_SELL'}]},
        {'symbol': 'MKR', 'exchange': 'BITKUB', 'last_price': 54073.53, 'percent_change': -10.58,
         'technicals': 'STRONG_SELL', 'is_interest': False, 'is_opened': False,
         'strategy': [{'time_frame': '30m', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '2h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '4h', 'strategy_summary': 'STRONG_SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1d', 'strategy_summary': 'STRONG_SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1W', 'strategy_summary': 'STRONG_SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1M', 'strategy_summary': 'STRONG_SELL', 'strategy_macd': 'STRONG_SELL'}]},
        {'symbol': 'ENJ', 'exchange': 'BITKUB', 'last_price': 45.7, 'percent_change': -14.19,
         'technicals': 'SELL', 'is_interest': False, 'is_opened': False,
         'strategy': [{'time_frame': '30m', 'strategy_summary': 'SELL', 'strategy_macd': 'SELL'},
                      {'time_frame': '1h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '2h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '4h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1d', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1W', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1M', 'strategy_summary': '', 'strategy_macd': ''}]},
        {'symbol': 'BAND', 'exchange': 'BITKUB', 'last_price': 122.15, 'percent_change': -17.8,
         'technicals': 'SELL', 'is_interest': False, 'is_opened': False,
         'strategy': [{'time_frame': '30m', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '2h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '4h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1d', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1W', 'strategy_summary': 'STRONG_SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1M', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'}]},
        {'symbol': 'COMP', 'exchange': 'BITKUB', 'last_price': 3507, 'percent_change': -10.06,
         'technicals': 'SELL', 'is_interest': False, 'is_opened': False,
         'strategy': [{'time_frame': '30m', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '2h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '4h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1d', 'strategy_summary': 'STRONG_SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1W', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1M', 'strategy_summary': 'STRONG_SELL', 'strategy_macd': 'STRONG_SELL'}]},
        {'symbol': 'KSM', 'exchange': 'BITKUB', 'last_price': 4125.83, 'percent_change': -11.28,
         'technicals': 'SELL', 'is_interest': False, 'is_opened': False,
         'strategy': [{'time_frame': '30m', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '2h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '4h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1d', 'strategy_summary': 'STRONG_SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1W', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1M', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'}]},
        {'symbol': 'DOT', 'exchange': 'BITKUB', 'last_price': 523.99, 'percent_change': -8.61,
         'technicals': 'SELL', 'is_interest': False, 'is_opened': False,
         'strategy': [{'time_frame': '30m', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '2h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '4h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1d', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1W', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1M', 'strategy_summary': 'STRONG_SELL', 'strategy_macd': 'STRONG_SELL'}]},
        {'symbol': 'NEAR', 'exchange': 'BITKUB', 'last_price': 277.5, 'percent_change': -13.01,
         'technicals': 'SELL', 'is_interest': False, 'is_opened': False,
         'strategy': [{'time_frame': '30m', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '2h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '4h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1d', 'strategy_summary': 'STRONG_SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1W', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1M', 'strategy_summary': 'NEUTRAL', 'strategy_macd': 'BUY'}]},
        {'symbol': 'SCRT', 'exchange': 'BITKUB', 'last_price': 168.38, 'percent_change': -12.65,
         'technicals': 'STRONG_SELL', 'is_interest': False, 'is_opened': False,
         'strategy': [{'time_frame': '30m', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '2h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '4h', 'strategy_summary': 'STRONG_SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1d', 'strategy_summary': 'STRONG_SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1W', 'strategy_summary': 'SELL', 'strategy_macd': 'SELL'},
                      {'time_frame': '1M', 'strategy_summary': 'SELL', 'strategy_macd': 'BUY'}]},
        {'symbol': 'GLM', 'exchange': 'BITKUB', 'last_price': 9.76, 'percent_change': -9.8,
         'technicals': 'SELL', 'is_interest': False, 'is_opened': False,
         'strategy': [{'time_frame': '30m', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '2h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '4h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1d', 'strategy_summary': 'STRONG_SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1W', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1M', 'strategy_summary': 'NEUTRAL', 'strategy_macd': 'STRONG_SELL'}]},
        {'symbol': 'DON', 'exchange': 'BITKUB', 'last_price': 0, 'percent_change': 0, 'technicals': '',
         'is_interest': True, 'is_opened': False,
         'strategy': [{'time_frame': '30m', 'strategy_summary': '', 'strategy_macd': ''},
                      {'time_frame': '1h', 'strategy_summary': '', 'strategy_macd': ''},
                      {'time_frame': '2h', 'strategy_summary': '', 'strategy_macd': ''},
                      {'time_frame': '4h', 'strategy_summary': '', 'strategy_macd': ''},
                      {'time_frame': '1d', 'strategy_summary': '', 'strategy_macd': ''},
                      {'time_frame': '1W', 'strategy_summary': '', 'strategy_macd': ''},
                      {'time_frame': '1M', 'strategy_summary': '', 'strategy_macd': ''}]},
        {'symbol': 'YFI', 'exchange': 'BITKUB', 'last_price': 642502.09, 'percent_change': -9.25,
         'technicals': 'SELL', 'is_interest': False, 'is_opened': False,
         'strategy': [{'time_frame': '30m', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '2h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '4h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1d', 'strategy_summary': 'STRONG_SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1W', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1M', 'strategy_summary': 'STRONG_SELL', 'strategy_macd': 'STRONG_SELL'}]},
        {'symbol': 'UNI', 'exchange': 'BITKUB', 'last_price': 276.43, 'percent_change': -12.67,
         'technicals': 'SELL', 'is_interest': False, 'is_opened': False,
         'strategy': [{'time_frame': '30m', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '2h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '4h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1d', 'strategy_summary': 'STRONG_SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1W', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1M', 'strategy_summary': 'STRONG_SELL', 'strategy_macd': 'STRONG_SELL'}]},
        {'symbol': 'AAVE', 'exchange': 'BITKUB', 'last_price': 4219.22, 'percent_change': -10.23,
         'technicals': 'SELL', 'is_interest': False, 'is_opened': False,
         'strategy': [{'time_frame': '30m', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '2h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '4h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1d', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1W', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1M', 'strategy_summary': 'STRONG_SELL', 'strategy_macd': 'STRONG_SELL'}]},
        {'symbol': 'ALPHA', 'exchange': 'BITKUB', 'last_price': 9.88, 'percent_change': -12.02,
         'technicals': 'SELL', 'is_interest': False, 'is_opened': False,
         'strategy': [{'time_frame': '30m', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '2h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '4h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1d', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1W', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1M', 'strategy_summary': '', 'strategy_macd': ''}]},
        {'symbol': 'OCEAN', 'exchange': 'BITKUB', 'last_price': 14.44, 'percent_change': -13.27,
         'technicals': 'SELL', 'is_interest': False, 'is_opened': False,
         'strategy': [{'time_frame': '30m', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '2h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '4h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1d', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1W', 'strategy_summary': 'NEUTRAL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1M', 'strategy_summary': '', 'strategy_macd': ''}]},
        {'symbol': 'SNX', 'exchange': 'BITKUB', 'last_price': 123.68, 'percent_change': -10.4,
         'technicals': 'SELL', 'is_interest': False, 'is_opened': False,
         'strategy': [{'time_frame': '30m', 'strategy_summary': 'SELL', 'strategy_macd': 'SELL'},
                      {'time_frame': '1h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '2h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '4h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1d', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1W', 'strategy_summary': 'STRONG_SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1M', 'strategy_summary': '', 'strategy_macd': ''}]},
        {'symbol': 'SAND', 'exchange': 'BITKUB', 'last_price': 96.4, 'percent_change': -12.58,
         'technicals': 'SELL', 'is_interest': False, 'is_opened': False,
         'strategy': [{'time_frame': '30m', 'strategy_summary': 'NEUTRAL', 'strategy_macd': 'SELL'},
                      {'time_frame': '1h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '2h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '4h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1d', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1W', 'strategy_summary': 'STRONG_SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1M', 'strategy_summary': '', 'strategy_macd': ''}]},
        {'symbol': 'BAL', 'exchange': 'BITKUB', 'last_price': 389.19, 'percent_change': -8.94,
         'technicals': 'SELL', 'is_interest': False, 'is_opened': False,
         'strategy': [{'time_frame': '30m', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '2h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '4h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1d', 'strategy_summary': 'STRONG_SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1W', 'strategy_summary': 'STRONG_SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1M', 'strategy_summary': '', 'strategy_macd': ''}]},
        {'symbol': 'CRV', 'exchange': 'BITKUB', 'last_price': 75.34, 'percent_change': -13.6,
         'technicals': 'SELL', 'is_interest': False, 'is_opened': False,
         'strategy': [{'time_frame': '30m', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '2h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '4h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1d', 'strategy_summary': 'STRONG_SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1W', 'strategy_summary': 'STRONG_SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1M', 'strategy_summary': '', 'strategy_macd': ''}]},
        {'symbol': 'KUB', 'exchange': 'BITKUB', 'last_price': 276.84, 'percent_change': -10.85,
         'technicals': 'SELL', 'is_interest': False, 'is_opened': False,
         'strategy': [{'time_frame': '30m', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '2h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '4h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1d', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1W', 'strategy_summary': 'BUY', 'strategy_macd': 'BUY'},
                      {'time_frame': '1M', 'strategy_summary': '', 'strategy_macd': ''}]},
        {'symbol': 'AXS', 'exchange': 'BITKUB', 'last_price': 1571.65, 'percent_change': -13.09,
         'technicals': 'SELL', 'is_interest': False, 'is_opened': False,
         'strategy': [{'time_frame': '30m', 'strategy_summary': 'SELL', 'strategy_macd': 'SELL'},
                      {'time_frame': '1h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '2h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '4h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1d', 'strategy_summary': 'STRONG_SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1W', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1M', 'strategy_summary': '', 'strategy_macd': ''}]},
        {'symbol': 'SUSHI', 'exchange': 'BITKUB', 'last_price': 105.88, 'percent_change': -13.8,
         'technicals': 'SELL', 'is_interest': False, 'is_opened': False,
         'strategy': [{'time_frame': '30m', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '2h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '4h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1d', 'strategy_summary': 'STRONG_SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1W', 'strategy_summary': 'SELL', 'strategy_macd': 'SELL'},
                      {'time_frame': '1M', 'strategy_summary': '', 'strategy_macd': ''}]},
        {'symbol': 'FTT', 'exchange': 'BITKUB', 'last_price': 1299.87, 'percent_change': -5.87,
         'technicals': 'SELL', 'is_interest': False, 'is_opened': False,
         'strategy': [{'time_frame': '30m', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '2h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '4h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1d', 'strategy_summary': 'STRONG_SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1W', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1M', 'strategy_summary': '', 'strategy_macd': ''}]},
        {'symbol': 'IMX', 'exchange': 'BITKUB', 'last_price': 52.56, 'percent_change': -15.65,
         'technicals': 'SELL', 'is_interest': False, 'is_opened': False,
         'strategy': [{'time_frame': '30m', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '2h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '4h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1d', 'strategy_summary': 'STRONG_SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1W', 'strategy_summary': '', 'strategy_macd': ''},
                      {'time_frame': '1M', 'strategy_summary': '', 'strategy_macd': ''}]},
        {'symbol': 'DYDX', 'exchange': 'BITKUB', 'last_price': 175.53, 'percent_change': -11.52,
         'technicals': 'SELL', 'is_interest': False, 'is_opened': False,
         'strategy': [{'time_frame': '30m', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '2h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '4h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1d', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1W', 'strategy_summary': '', 'strategy_macd': ''},
                      {'time_frame': '1M', 'strategy_summary': '', 'strategy_macd': ''}]},
        {'symbol': 'ENS', 'exchange': 'BITKUB', 'last_price': 447.87, 'percent_change': -15.5,
         'technicals': 'SELL', 'is_interest': False, 'is_opened': False,
         'strategy': [{'time_frame': '30m', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '2h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '4h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1d', 'strategy_summary': 'STRONG_SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1W', 'strategy_summary': '', 'strategy_macd': ''},
                      {'time_frame': '1M', 'strategy_summary': '', 'strategy_macd': ''}]},
        {'symbol': 'BOBA', 'exchange': 'BITKUB', 'last_price': 0, 'percent_change': 0, 'technicals': '',
         'is_interest': True, 'is_opened': False,
         'strategy': [{'time_frame': '30m', 'strategy_summary': '', 'strategy_macd': ''},
                      {'time_frame': '1h', 'strategy_summary': '', 'strategy_macd': ''},
                      {'time_frame': '2h', 'strategy_summary': '', 'strategy_macd': ''},
                      {'time_frame': '4h', 'strategy_summary': '', 'strategy_macd': ''},
                      {'time_frame': '1d', 'strategy_summary': '', 'strategy_macd': ''},
                      {'time_frame': '1W', 'strategy_summary': '', 'strategy_macd': ''},
                      {'time_frame': '1M', 'strategy_summary': '', 'strategy_macd': ''}]},
        {'symbol': 'ILV', 'exchange': 'BITKUB', 'last_price': 17000.03, 'percent_change': -9.97,
         'technicals': 'STRONG_SELL', 'is_interest': False, 'is_opened': False,
         'strategy': [{'time_frame': '30m', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '2h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '4h', 'strategy_summary': 'STRONG_SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1d', 'strategy_summary': 'STRONG_SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1W', 'strategy_summary': '', 'strategy_macd': ''},
                      {'time_frame': '1M', 'strategy_summary': '', 'strategy_macd': ''}]},
        {'symbol': 'GALA', 'exchange': 'BITKUB', 'last_price': 7.31, 'percent_change': -16.55,
         'technicals': 'SELL', 'is_interest': False, 'is_opened': False,
         'strategy': [{'time_frame': '30m', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '2h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '4h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1d', 'strategy_summary': 'STRONG_SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1W', 'strategy_summary': '', 'strategy_macd': ''},
                      {'time_frame': '1M', 'strategy_summary': '', 'strategy_macd': ''}]},
        {'symbol': 'GT', 'exchange': 'BITKUB', 'last_price': 200.75, 'percent_change': -6.12,
         'technicals': 'SELL', 'is_interest': False, 'is_opened': False,
         'strategy': [{'time_frame': '30m', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '2h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '4h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1d', 'strategy_summary': 'STRONG_SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1W', 'strategy_summary': '', 'strategy_macd': ''},
                      {'time_frame': '1M', 'strategy_summary': '', 'strategy_macd': ''}]},
        {'symbol': 'SGB', 'exchange': 'BITKUB', 'last_price': 0, 'percent_change': 0, 'technicals': '',
         'is_interest': True, 'is_opened': False,
         'strategy': [{'time_frame': '30m', 'strategy_summary': '', 'strategy_macd': ''},
                      {'time_frame': '1h', 'strategy_summary': '', 'strategy_macd': ''},
                      {'time_frame': '2h', 'strategy_summary': '', 'strategy_macd': ''},
                      {'time_frame': '4h', 'strategy_summary': '', 'strategy_macd': ''},
                      {'time_frame': '1d', 'strategy_summary': '', 'strategy_macd': ''},
                      {'time_frame': '1W', 'strategy_summary': '', 'strategy_macd': ''},
                      {'time_frame': '1M', 'strategy_summary': '', 'strategy_macd': ''}]},
        {'symbol': 'LYXE', 'exchange': 'BITKUB', 'last_price': 390, 'percent_change': -13.43,
         'technicals': 'SELL', 'is_interest': False, 'is_opened': False,
         'strategy': [{'time_frame': '30m', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '2h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '4h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1d', 'strategy_summary': 'STRONG_SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1W', 'strategy_summary': '', 'strategy_macd': ''},
                      {'time_frame': '1M', 'strategy_summary': '', 'strategy_macd': ''}]},
        {'symbol': 'GF', 'exchange': 'BITKUB', 'last_price': 59.55, 'percent_change': -4.52,
         'technicals': 'SELL', 'is_interest': False, 'is_opened': False,
         'strategy': [{'time_frame': '30m', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '2h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '4h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1d', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1W', 'strategy_summary': '', 'strategy_macd': ''},
                      {'time_frame': '1M', 'strategy_summary': '', 'strategy_macd': ''}]},
        {'symbol': 'EXFI', 'exchange': 'BITKUB', 'last_price': 0, 'percent_change': 0, 'technicals': '',
         'is_interest': True, 'is_opened': False,
         'strategy': [{'time_frame': '30m', 'strategy_summary': '', 'strategy_macd': ''},
                      {'time_frame': '1h', 'strategy_summary': '', 'strategy_macd': ''},
                      {'time_frame': '2h', 'strategy_summary': '', 'strategy_macd': ''},
                      {'time_frame': '4h', 'strategy_summary': '', 'strategy_macd': ''},
                      {'time_frame': '1d', 'strategy_summary': '', 'strategy_macd': ''},
                      {'time_frame': '1W', 'strategy_summary': '', 'strategy_macd': ''},
                      {'time_frame': '1M', 'strategy_summary': '', 'strategy_macd': ''}]},
        {'symbol': 'SOL', 'exchange': 'BITKUB', 'last_price': 2695.06, 'percent_change': -13.34,
         'technicals': 'SELL', 'is_interest': False, 'is_opened': False,
         'strategy': [{'time_frame': '30m', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '2h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '4h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1d', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1W', 'strategy_summary': '', 'strategy_macd': ''},
                      {'time_frame': '1M', 'strategy_summary': '', 'strategy_macd': ''}]},
        {'symbol': 'AVAX', 'exchange': 'BITKUB', 'last_price': 2256.02, 'percent_change': -15.67,
         'technicals': 'SELL', 'is_interest': False, 'is_opened': False,
         'strategy': [{'time_frame': '30m', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '2h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '4h', 'strategy_summary': 'SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1d', 'strategy_summary': 'STRONG_SELL', 'strategy_macd': 'STRONG_SELL'},
                      {'time_frame': '1W', 'strategy_summary': '', 'strategy_macd': ''},
                      {'time_frame': '1M', 'strategy_summary': '', 'strategy_macd': ''}]}]
    mycursor = mydb.cursor()
    for i in interest:
        sql = """insert into tbt_interest (id, exchange, symbol, last_price, percent_change, technicals, is_interest, 
           is_opened, last_update) values (%s, %s, %s, %s, %s, %s, 0, 0, CURRENT_TIMESTAMP);"""
        val = (nanoid.generate(size=20), i['exchange'], i['symbol'], i['last_price'], i['percent_change'], i['technicals'])
        print(val)
        mycursor.execute(sql, val)

        # loop strategy
        for x in i['strategy']:
            log.print_color(
                f"time frame: {x['time_frame']}\nsummary: {x['strategy_summary']}\nmacd: {x['strategy_macd']}")
        print(mycursor.rowcount, "record inserted.")

    mydb.commit()


if __name__ == '__main__':
    # main()
    # print(investment)
    insert_interest()
    sys.exit(0)
